#dist: bionic
#sudo: required

language: go
go:
  - 1.12.6

go_import_path: github.com/alibaba/pouch

script:
  - make build
  - make install
  - sudo cp ${GOPATH}/bin/pouch /usr/local/bin
  - sudo cp ${GOPATH}/bin/pouchd /usr/local/bin
  #- cd ../..
  #- git clone https://github.com/Abhisheknishant/containerd
  #- cd containerd
  #- make BUILDTAGS=no_cri
  #- make install
  #- sudo cp ${GOPATH}/bin/containerd /usr/local/bin
  #- ./hack/install/install_containerd.sh
  - wget https://github.com/containerd/containerd/releases/download/v1.2.14/containerd-1.2.14.linux-amd64.tar.gz
  - sudo tar -xvf containerd-1.2.14.linux-amd64.tar.gz
  - sudo cp bin/containerd /usr/local/bin
  #- while sleep 5m; do echo "=====[ $SECONDS seconds, still building... ]====="; done &
  - while sleep 10m; do sudo pouchd; done &
  - sudo /usr/local/bin/pouch run -d --name TestRunWithDefaultShm registry.hub.docker.com/library/busybox:1.28 top
  - sudo /usr/local/bin/pouch exec TestRunWithDefaultShm df -k /dev/shm
