#dist: bionic
sudo: required

language: go
go:
  - 1.12.6

go_import_path: github.com/alibaba/pouch

script:
  - sudo make build
  - sudo make install
  - sudo ./hack/install/install_containerd.sh
  - sudo pouchd
  - sudo /usr/local/bin/pouch run -d --name TestRunWithDefaultShm registry.hub.docker.com/library/busybox:1.28 top
  - sudo /usr/local/bin/pouch exec TestRunWithDefaultShm df -k /dev/shm
