#dist: bionic
#sudo: required

language: go
go:
  - 1.12.6

go_import_path: github.com/alibaba/pouch

script:
  - make build
  - make install
  - sudo cp ${GOPATH}/bin/pouch /usr/local/bin
  - sudo cp ${GOPATH}/bin/pouchd /usr/local/bin
  #- cd ../..
  #- git clone https://github.com/Abhisheknishant/containerd
  #- cd containerd
  #- make BUILDTAGS=no_cri
  #- make install
  #- sudo cp ${GOPATH}/bin/containerd /usr/local/bin
  #- ./hack/install/install_containerd.sh
  - wget https://github.com/containerd/containerd/releases/download/v1.2.14/containerd-1.2.14.linux-amd64.tar.gz
  - sudo tar -xvf containerd-1.2.14.linux-amd64.tar.gz
  - sudo cp bin/containerd /usr/local/bin
  #- while sleep 5m; do echo "=====[ $SECONDS seconds, still building... ]====="; done &
  - touch out.txt
  - while sleep 10m; do sudo pouchd > out.txt; done &
  - find . -name out.txt
  - cat out.txt
  - sudo /usr/local/bin/pouch run -d --name TestRunWithDefaultShm registry.hub.docker.com/library/busybox:1.28 top
  - touch out1.txt
  - while sleep 10m; do sudo pouchd 2>&1 | tee out1.txt; done &
  - find . -name out1.txt
  - cat out1.txt
  - touch out2.txt
  - while sleep 10m; do echo "printing1111111111" 2>&1 | tee out2.txt; done &
  - cat out2.txt
  - touch out3.txt
  - while sleep 10m; do echo "printing2222222222222" 2>&1 | tee out3.txt; done &
  - cat out3.txt
  - sudo /usr/local/bin/pouch exec TestRunWithDefaultShm df -k /dev/shm
